better error message for github-repos

diff --git a/bin/github-repos b/bin/github-repos
--- a/bin/github-repos
+++ b/bin/github-repos
@@ -27,7 +27,8 @@ reposurl="$apiurl/user/repos?$authparam"
 # make sure we're authenticated
 if ! headers "$authurl" | grep -q "Status: 200 OK"
 then
-    echo >&2 "authentication failed"
+    echo "github-repos: Authentication failed. Check the given user and " \
+        "are valid." 1>&2
     exit 1
 fi
 
