small cbk-pull-github tweaks

diff --git a/share/cbk/cbk-pull-github b/share/cbk/cbk-pull-github
--- a/share/cbk/cbk-pull-github
+++ b/share/cbk/cbk-pull-github
@@ -8,7 +8,7 @@
 set -e
 
 abort() {
-    echo "at=cbk-pull-github error=\"$@\"" 1>&2
+    echo "command=cbk-pull-github at=error msg=\"$@\"" 1>&2
     exit 1
 }
 
@@ -20,7 +20,7 @@ abort "the directory set in CBK_GITHUB_DIR does not exist"
 [ -z "$CBK_GITHUB_USER" ] && abort "CBK_GITHUB_USER not set"
 [ -z "$CBK_GITHUB_TOKEN" ] && abort "CBK_GITHUB_TOKEN not set"
 
-# Grab the list of all repositories this set of credentials has access to
+# Iterate over all repositories this set of credentials has access to
 github-repos "$CBK_GITHUB_USER" "$CBK_GITHUB_TOKEN" |
 while read line; do
     giturl="$line"
@@ -33,8 +33,9 @@ while read line; do
     repodir="$CBK_GITHUB_DIR/$user/$repo.git"
     cloneurl="https://$CBK_GITHUB_USER:$CBK_GITHUB_TOKEN@github.com/$user/$repo"
 
+    # Skip mirroring if the repository is included in the exclude list
     skip=
-    for exclude in "$CBK_GITHUB_EXCLUDE"; do
+    for exclude in "$CBK_GITHUB_EXCLUDES"; do
         if [ "$repo" = "$exclude" ]; then
             skip=1
             break
@@ -44,6 +45,7 @@ while read line; do
     if [ "$skip" ]; then
         echo "command=cbk-pull-github at=skip git=$giturl dir=$repodir" 1>&2
         continue
+    # Otherwise mirror the remote repository onto the local data directory
     else
         echo "command=cbk-pull-github at=start git=$giturl dir=$repodir" 1>&2
         git-mirror "$cloneurl" "$repodir"
